### ISSUE TITLE
Input disappears when using 'prev'/'next' navigation

### ISSUE THREAD

**Issue by lidijarad** [proversity-org/xblock-free-text-response#12]
If a user saves their responses and navigates away from the free-text response xblock, without a page reload, their response disappears. It appears if the page is reloaded since the save button writes the data to the user state and it is displayed on page reload. Will need to save the response using localstorage or something?

**Comment by mariushuman** [comment]
@lidijarad what is suppose to happen when you now save and submit your answer?

I can confirm, That when you select 'save' and click next to go to another unit, and click previous, it now displays the text - Great.

But when you select 'save' and then 'submit', then select Next and then previous again, the answer is empty. Even when you do a hard refresh. 
The only way to check was to go and view it on the progress tab.

Is this expected behaviour? From a learners side this can be confusing as it appears that the answer(s) was/is not submitted.

**Comment by lidijarad** [comment]
@mariushuman, definitely not the expected behaviour. Please send me a link.

**Comment by nicovanniekerk** [comment]
this was fixed with the localstorage save we are doing now.
